// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJY-pORPixU1r7ZYHY-euDgmL4E_xsj4Q',
    appId: '1:1046560322662:web:4ba734d40293b28b1869a7',
    messagingSenderId: '1046560322662',
    projectId: 'trust-os-76485',
    authDomain: 'trust-os-76485.firebaseapp.com',
    storageBucket: 'trust-os-76485.firebasestorage.app',
    measurementId: 'G-JCYLY2PRX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOPV0hnlzBh0sGwS4z8Yzzn6rXvfhWik',
    appId: '1:1046560322662:android:e1e5e4ef6dfb6d291869a7',
    messagingSenderId: '1046560322662',
    projectId: 'trust-os-76485',
    storageBucket: 'trust-os-76485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcf9sKlPnwG0y6G-apDYh1O7d5Au1SrN8',
    appId: '1:1046560322662:ios:6e615d975e5a68961869a7',
    messagingSenderId: '1046560322662',
    projectId: 'trust-os-76485',
    storageBucket: 'trust-os-76485.firebasestorage.app',
    iosBundleId: 'com.example.flutterSandbox',
  );
}
